matlab-tests:
    stage: test
    tags:
        - on-prem
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
        - mw -using $CURRENT_MATLAB_RELEASE matlab -batch "openProject(pwd); runTests;"
    cache:
        paths:
            - work/*.slxc
    artifacts:
        name: "$env:CI_PROJECT_NAME-$env:CI_JOB_STAGE-$env:CI_COMMIT_REF_NAME-$env:CI_JOB_STARTED_AT"
        paths:
            - work/TestReport.pdf
        when: always
        reports:
            junit: work/results.xml
